/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.projetolpooe2luiseduardoatunes.view;

import br.edu.ifsul.cc.lpoo.projetolpooe2_luiseduardoantunes.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.projetolpooe2_luiseduardoantunes.model.Cliente;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class TelaClientes extends javax.swing.JFrame {
    
    PersistenciaJPA jpa;

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
        listarClientes();
    }
    
    public void listarClientes() {
        lstClientes.clearSelection();
        jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        List<Cliente> lista = jpa.getClientes("Lista: ");
        System.out.println(lista);
        DefaultListModel modeloLista = new DefaultListModel<>();
        for (Cliente m : lista) {
            modeloLista.addElement(m);
        }
        lstClientes.setModel(modeloLista);
        jpa.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clientes cadastrados:");

        jLabel2.setText("Nomes:");

        jScrollPane1.setViewportView(lstClientes);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(btnVisualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        c.setNome(JOptionPane.showInputDialog("Informe o nome do cliente:"));
        c.setEndereco(JOptionPane.showInputDialog("Informe o endereço do cliente:"));
        c.setEmail(JOptionPane.showInputDialog("Informe o email do cliente:"));
        c.setTelefone(JOptionPane.showInputDialog("Informe o telefone do cliente:"));

        jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        jpa.persist(c);
        jpa.fecharConexao();

        listarClientes();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {
            int confirmacaoDel = JOptionPane.showConfirmDialog(rootPane,
                    "Tem certeza que deseja remover cliente " + clienteSelecionado.getNome()+"?");
            if (confirmacaoDel == JOptionPane.YES_OPTION) {
                try {
                    jpa = new PersistenciaJPA();
                    jpa.conexaoAberta();
                    jpa.remover(clienteSelecionado);
                    jpa.fecharConexao();
                    listarClientes();

                } catch (Exception e) {
                    System.err.println("Erro ao excluir cliente: " + e.getMessage());
                } finally {
                    jpa.fecharConexao();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Nenhuma cliente selecionado");
        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {
            try {
                jpa = new PersistenciaJPA();
                jpa.conexaoAberta();
                TelaCadastroCliente telaCadastro = new TelaCadastroCliente(this, true);
                telaCadastro.setCliente(clienteSelecionado);
                telaCadastro.setVisible(true);
                listarClientes();
            } catch (Exception e) {
                System.err.println("Erro ao editar cliente: " + e.getMessage());
            } finally {
                jpa.fecharConexao();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para editar");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        Cliente clienteSelecionado = lstClientes.getSelectedValue();
        if (clienteSelecionado != null) {
            JOptionPane.showMessageDialog(rootPane, "Nome: "+clienteSelecionado.getNome()+"\n"+
                    "Endereço: "+clienteSelecionado.getEndereco()+"\n"+
                    "Email: "+clienteSelecionado.getEmail()+"\n"+
                    "Telefone: "+clienteSelecionado.getTelefone());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para visualizar");
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        String textoBusca = txtBusca.getText().trim();
        
        if(textoBusca.isEmpty()){
            listarClientes();
            return;
        }
        
        lstClientes.clearSelection();
        jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        List<Cliente> lista = jpa.getClientes(textoBusca);
        System.out.println("Lista: " + lista);
        DefaultListModel modeloLista = new DefaultListModel<>();
        for (Cliente c : lista) {
            modeloLista.addElement(c);
        }
        lstClientes.setModel(modeloLista);
        jpa.fecharConexao();
    }//GEN-LAST:event_txtBuscaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Cliente> lstClientes;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
