/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.projetolpooe2luiseduardoatunes.view;

import br.edu.ifsul.cc.lpoo.projetolpooe2_luiseduardoantunes.dao.PersistenciaJPA;
import br.edu.ifsul.cc.lpoo.projetolpooe2_luiseduardoantunes.model.Reserva;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaReservas extends javax.swing.JFrame {
    
    PersistenciaJPA jpa;

    /**
     * Creates new form TelaReservas
     */
    public TelaReservas() {
        initComponents();
        listarReservas();
    }
    
    public void listarReservas(){
        lstReservas.clearSelection();
        jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        List<Reserva> lista = jpa.getReservas("Lista: ");
        System.out.println(lista);
        DefaultListModel modeloLista = new DefaultListModel<>();
        for (Reserva m : lista) {
            modeloLista.addElement(m);
        }
        lstReservas.setModel(modeloLista);
        jpa.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReservas = new javax.swing.JList<>();
        btnAdicionar = new javax.swing.JButton();
        btnEdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reservas Cadastradas");

        jLabel2.setText("Livro Reservado:");

        jScrollPane1.setViewportView(lstReservas);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEdicionar.setText("Editar");
        btnEdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusca)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualizar)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEdicionar)
                    .addComponent(btnRemover)
                    .addComponent(btnVisualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        Reserva r = new Reserva();
        
        try {
                jpa = new PersistenciaJPA();
                jpa.conexaoAberta();
                TelaCadastroReserva telaCadastro = new TelaCadastroReserva(this, true);
                telaCadastro.setReserva(r);
                telaCadastro.setVisible(true);
                listarReservas();
            } catch (Exception e) {
                System.err.println("Erro ao adicionar reserva: " + e.getMessage());
            } finally {
                jpa.fecharConexao();
            }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicionarActionPerformed
        // TODO add your handling code here:
        Reserva reservaSelecionada = lstReservas.getSelectedValue();
        if (reservaSelecionada != null) {
            try {
                jpa = new PersistenciaJPA();
                jpa.conexaoAberta();
                TelaCadastroReserva telaCadastro = new TelaCadastroReserva(this, true);
                telaCadastro.setReserva(reservaSelecionada);
                telaCadastro.setVisible(true);
                listarReservas();
            } catch (Exception e) {
                System.err.println("Erro ao editar reserva: " + e.getMessage());
            } finally {
                jpa.fecharConexao();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma reserva para editar");
        }
    }//GEN-LAST:event_btnEdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        Reserva reservaSelecionada = lstReservas.getSelectedValue();
        if (reservaSelecionada != null) {
            int confirmacaoDel = JOptionPane.showConfirmDialog(rootPane,
                    "Tem certeza que deseja remover a reserva do livro " + reservaSelecionada.getLivroReservado()+"?");
            if (confirmacaoDel == JOptionPane.YES_OPTION) {
                try {
                    jpa = new PersistenciaJPA();
                    jpa.conexaoAberta();
                    jpa.remover(reservaSelecionada);
                    jpa.fecharConexao();
                    listarReservas();

                } catch (Exception e) {
                    System.err.println("Erro ao excluir reserva: " + e.getMessage());
                } finally {
                    jpa.fecharConexao();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Nenhuma reserva selecionado");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        Reserva reservaSelecionada = lstReservas.getSelectedValue();
        if (reservaSelecionada != null) {
            Calendar calendar = reservaSelecionada.getDataInicio();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = sdf.format(calendar.getTime());
            
            calendar = reservaSelecionada.getDataFim();
            sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate1 = sdf.format(calendar.getTime());
            
            JOptionPane.showMessageDialog(rootPane, "Livro reservado: "+reservaSelecionada.getLivroReservado()+"\n"+
                    "Cliente: "+reservaSelecionada.getCliente().getNome()+"\n"+
                    "Bibliotecario: "+reservaSelecionada.getBibliotecario().getNome()+"\n"+
                    "Data inicial da reserva: "+formattedDate+"\n"+
                    "Data final da reserva: "+formattedDate1);
                    
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para visualizar");
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        String textoBusca = txtBusca.getText().trim();
        
        if(textoBusca.isEmpty()){
            listarReservas();
            return;
        }
        
        lstReservas.clearSelection();
        jpa = new PersistenciaJPA();
        jpa.conexaoAberta();
        List<Reserva> lista = jpa.getReservas(textoBusca);
        System.out.println("Lista: " + lista);
        DefaultListModel modeloLista = new DefaultListModel<>();
        for (Reserva b : lista) {
            modeloLista.addElement(b);
        }
        lstReservas.setModel(modeloLista);
        jpa.fecharConexao();
    }//GEN-LAST:event_txtBuscaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Reserva> lstReservas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
